/** SEO-critical JSON-LD — byte-for-byte from V9 HTML (CURSOR-PROMPT). */

export const jsonLdOrganization =
  '{"@context":"https://schema.org","@type":"Organization","name":"Princess Promotions Reviews","url":"https://princesspromtionsreviews.com/","description":"Independent consumer review site covering Princess Promotions Future Cruise Packages"}'

export const jsonLdArticle =
  '{"@context":"https://schema.org","@type":"Article","headline":"Princess Promotions Reviews: Scam or Legit?","description":"Independent review of Princess Promotions Future Cruise Packages based on BBB complaints, cruise forum data, and consumer feedback.","author":{"@type":"Organization","name":"Princess Promotions Reviews"},"publisher":{"@type":"Organization","name":"Princess Promotions Reviews"},"datePublished":"2026-03-01","dateModified":"2026-03-25","mainEntityOfPage":{"@type":"WebPage","@id":"https://princesspromtionsreviews.com/"},"aggregateRating":{"@type":"AggregateRating","ratingValue":"3.1","bestRating":"5","worstRating":"1","ratingCount":"247","reviewCount":"247"}}'

export const jsonLdFaq =
  '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Is Princess Promotions a scam?","acceptedAnswer":{"@type":"Answer","text":"Based on our review, no. FCCs are real and work. However, there are documented issues with hotel credits, additional charges, and post-sale support."}},{"@type":"Question","name":"Is Princess Promotions the same as Princess Cruises?","acceptedAnswer":{"@type":"Answer","text":"No. Operated by Open Network Exchange (ONE Inc.). FCCs go through Princess Cruises; hotel certificates through Princess Promotions."}},{"@type":"Question","name":"How do hotel credits actually work?","acceptedAnswer":{"@type":"Answer","text":"May apply at 50% of stated value. Platform prices often higher than Booking.com and Expedia. Always compare and get written confirmation."}},{"@type":"Question","name":"Can I cancel my Princess Promotions package?","acceptedAnswer":{"@type":"Answer","text":"7-day cancellation window. After that, significantly harder. Send written cancellation immediately if in doubt."}},{"@type":"Question","name":"Are cruise credits cheaper than booking direct?","acceptedAnswer":{"@type":"Answer","text":"FCCs provide real savings. Hotel components often don\'t match paper value. Evaluate separately."}}]}'
